name: Deployment

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APPLICATION_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL_ADDRESS}}
